---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slp.name" . }}
  namespace:  {{ .Values.namespace }}
  labels:
    {{- include "slp.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ include "slp.name" . }}-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slp.name" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "slp.name" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ include "slp.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
