# permissions for end users to edit opaadmissioncontrollerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opaadmissioncontrollerdeployment-editor-role
rules:
- apiGroups:
  - opa.twdps.io
  resources:
  - opaadmissioncontrollerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opa.twdps.io
  resources:
  - opaadmissioncontrollerdeployments/status
  verbs:
  - get
