# permissions for end users to view opaadmissioncontrollerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opaadmissioncontrollerdeployment-viewer-role
rules:
- apiGroups:
  - opa.twdps.io
  resources:
  - opaadmissioncontrollerdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opa.twdps.io
  resources:
  - opaadmissioncontrollerdeployments/status
  verbs:
  - get
